import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Navbar from 'components/navbar';
import Footer from 'components/footer';
import Hero from 'components/hero';
import Team from 'components/team';
import Testimonial from 'components/testimonial';
import Loader from 'components/loader';
import { useEffect, useState } from 'react';

export default function Home() {
  const [data, setData] = useState(null)
  const [isLoading, setLoading] = useState(false)

  useEffect(() => {
    setLoading(true)
        fetch('http://127.0.0.1:1337/api/home?populate=*')
          .then((res) => res.json())
          .then((data) => {
            setData(data)
            setLoading(false)
          })
  }, [])

  if (isLoading) return <Loader></Loader>
  if (!data) return <p>No profile data</p>

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar></Navbar>
        {Object.values(data.data.attributes.dyanamo).map((obj, indx) => (
          {
            "page.hero": <Hero data={data.data.attributes.dyanamo[indx]}/>,
            "page.our-team": <Team data={data.data.attributes.dyanamo[indx]}/>,
            "page.testimonial": <Testimonial data={data.data.attributes.dyanamo[indx]} />,
          }[obj.__component]
        ))}
        <Footer></Footer>
      </main>
    </>
  )
}

// export async function getServerSideProps(context) {
//   // Fetch data from external API
//   const res = await fetch(`http://127.0.0.1:1337/api/home?populate=*`);
//   const data = await res.json();

//   return {
//     props: { data }, // will be passed to the page component as props
//   }
// }